### ISSUE TITLE
[ENHANCEMENT] Use different colored names and text bubbles for different named characters

### ISSUE THREAD

**Issue by NintendoManiac64** [kaihordewebui/kaihordewebui.github.io#18]
This is particularly noticeable in the "Class Reunion" scenario where, currently, all named characters other than `You` have the same color - they are red while you are blue, while the chat bubbles are they are grey while you are green.

My suggestion is a simple one then - have every named character be a different color.  It could be random, or maybe it could be in a sort of set order kind of like in video games where it's usually something like P1: blue, P2: red, P3: yellow, P4: green etc so each subsequent different name would just take on whatever the next predefined color is.

It may be worth noting that the chat bot can introduce new characters which is why I figured it'd be best to tie the colors to names (assuming that's even possible) whereby, whenever a name is used that wasn't previously used, it chooses another color.

**Comment by LostRuins** [comment]
Wow this is something I haven't thought of. Good idea. I will add it to the todo.

**Comment by LostRuins** [comment]
This is added to Kobold Lite.
