### ISSUE TITLE
"Throbber" (loading spinner) when generating a new message in the "Edit" view "sticks" to up/right/down/left

### ISSUE THREAD

**Issue by NintendoManiac64** [kaihordewebui/kaihordewebui.github.io#19]
Tested in Pale Moon 32.1.1 and 32.2.0 as well as LibreWolf 112.0.2-1 on Linux Mint (occurs on both Xfce 20.3 and Cinnamon 21.1).

The throbber (loading spinner) used to spin evenly and  smoothly. However, since a week (?) ago, it now "sticks" to up/right/down/left, making for a very jerky appearance.

I suppose it's possible that this is an intentional design change but, to be honest, I find the new design more distracting and annoying.

If you're not seeing this on your side then I can record a short video showing it and then compare it to a traditional "smooth" spinning throbber (there's one right on this very Github page when javascript is disabled).

**Comment by LostRuins** [comment]
Yes this is intentional. Some users have complained that the constant spin animation was slowing down their PC, so I changed it to an animation that doesn't run constantly. Although maybe I should just change it to a gif or something

**Comment by NintendoManiac64** [comment]
Maybe this would be one of the perfect use-cases for the rarely-talked about animated PNG format?  The main benefit being that it supports alpha transparency which is presumably the main reason you didn't use a GIF or the like.

(fun fact: throbbers with alpha transparency was actually one of the main reasons Mozilla invented the APNG format back in the late 2000s, because the throbbers in Firefox at the time lacked alpha transparency)

More people don't know about the format because it was hampered by developer politics (tl;dr: Mozilla wanted APNG, Google wanted animated WebP) until Apple chose it as the basis of iMessage's "stickers" but, by that point, the combination of smart phones, tablets, and social media caused GIF to regain popularity and turn into "MP3 MKII" (aka, even though newer and better formats existed, less tech-savvy users only knew of the old standard and caused it to become even more entrenched)

...though, since both APNG and animated WebP have widespread browser support, I suppose either format would work. Just... not GIF, please (it's a bit of a sore spot for me if you couldn't tell... my only consolation is that GIF can't do HDR nor 3D so eventually it'll *have* to be superseded even by "normies" once holodecks are commonplace)

**Comment by LostRuins** [comment]
Fixed, now has a nicer stop motion effect which is also processor friendly.
