### ISSUE TITLE
"Enter" key does not submit typed message in Pale Moon outside of "Aesthetic Chat UI"

### ISSUE THREAD

**Issue by NintendoManiac64** [kaihordewebui/kaihordewebui.github.io#2]
This occurs on both Windows 7 SP1 and Linux Mint 20.3, and I tested on Windows using a newly-downloaded copy of Pale Moon Portable (see the attached video).

Simply put, the "Enter" key does not work in Pale Moon for submitting the message that you typed when using the "Aesthetic Chat UI".  This issue does not occur in LibreWolf.

More information from https://repo.palemoon.org/MoonchildProductions/UXP/issues/2153

> This is likely because of our change in keypress handling as introduced in [74b3ce90d7](https://repo.palemoon.org/MoonchildProductions/UXP/commit/74b3ce90d73f576a36888c06e413b99b61687b80) that was a response to the bad practice on the web to use onkeypress handlers to attempt to "filter" inputs (instead of using the normal methods available in HTML to do so). We aligned with the behavior in other mainstream browsers in this case even though I considered it webmaster error.

> If websites use onkeypress enter to trigger script processing of a message, then that will likely no longer work, and will need a scripting change on the affected websites.

See the following attached video for a demonstration of the issue (do not mind the messages in the video speaking of an issue with scrolling; I didn't realize at the time that the "autoscroll" setting on Kobold is disabled by default):

[video.webm](https://user-images.githubusercontent.com/11896003/224823392-5d32a606-43df-4088-bd49-640e3c3dff1f.webm)

**Comment by LostRuins** [comment]
Hello @NintendoManiac64 thanks for bringing this to my attention. This is a very poor choice on Pale Moon's part. 

Nevertheless, I have deployed a change that changes the trigger event from KeyPress to KeyUp, which should hopefully solve this issue. Could you help me see if that resolves the problem? Thanks.

**Comment by jobbautista9** [comment]
Hi, it seems further digging by one of Pale Moon's developers reveal that your website is using global `window.event`. We don't plan to support this in the future as it has never been a part of the standard, and though mainstream browsers like Chrome and Firefox (and do note that Firefox supported this pretty late, starting with version 66) currently support it, the [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/event) says this is deprecated and recommends doing away with it. Please use the event passed into the handler instead. Not only will this ensure compatibility across all modern browsers, it will also remove potential fragility in your JavaScript. :) It shouldn't take long to fix.

**Comment by LostRuins** [comment]
Thank you for highlighting this, @jobbautista9 . I have now switched it to the local event handler and it seems to be working fine. 

@NintendoManiac64 , can you confirm if this issue is now resolved for you?

**Comment by NintendoManiac64** [comment]
Confirmed that it's working now.

That being said, since the issue was initially mis-diagnosed, it might be a good idea to revert commit a214c01 where you switched to KeyUp.

Also, the head Pale Moon dev actually says using KeyDown would make more sense, but I'm not sure how applicable that'd be if we mis-diagnosed the issue in the first place.

**Comment by LostRuins** [comment]
@NintendoManiac64 okay, the KeyUp change has been reverted back to original. If everything is fine, I will mark the issue as resolved.

**Comment by NintendoManiac64** [comment]
Actually, it seems like the original behavior results in the enter key not even being able to have the chat bot generate another message even in the likes of Firefox.  I wonder if the "KeyDown" behavior suggested by the head Pale Moon dev would actually solve that without having the line-break issues that "KeyUp" was causing?

**Comment by LostRuins** [comment]
Alright @NintendoManiac64 I've switched to KeyDown instead. Can you see if it works better for you? 

For my own testing I use the latest versions of Firefox, Opera, Chrome, and all of them seem to work equally fine regardless of which keyup/keydown/keypress event I was handling. So I can't really compare myself.

**Comment by NintendoManiac64** [comment]
Hmm, peculiar.  KeyDown seems to behave exactly the same as the original behavior...

I think what should be done is to revert to the original behavior and then figure out some other way to make the enter key work when you have not typed anything in order to make the chat bot generate a new message - perhaps something worthy of opening a separate issue?

**Comment by LostRuins** [comment]
Preventing enter key from triggering when the textbox is empty is intentional - you normally don't want to send a blank reply. Most other chat apps have the same behavior. If you want to send a blank message, you can manually trigger it with the Submit button. 

Alright, marking this issue as closed. Do open another one if you encounter further issues. Thanks.

**Comment by NintendoManiac64** [comment]
> Most other chat apps have the same behavior. If you want to send a blank message, you can manually trigger it with the Submit button.

But in real life, you don't have the ability to "force" the other party to send another message like you do with chat bots.

**Comment by LostRuins** [comment]
Understood - but people will normally interact with a chat UI in the same way and expect similar results.

I can probably add an exception to permit it for the aesthetic chat UI as it is single lined. 

For the default normal UI, this will be very disruptive as people use it to input multi-lined story prompts as well.

**Comment by NintendoManiac64** [comment]
Idea - you know how shift+enter inserts a line-break?  Well, *starting* a message with a line-break makes absolutely no sense, so maybe shift+enter, when nothing is typed, can send the message instead?

(fun fact: the "chat" function on pixiv has shift+enter always function as "send message" so it's not unheard of)

**Comment by LostRuins** [comment]
Shift-enter sending a message instead would be a super unintuitive behavior. 
I'll just enable sending empty messages with the enter button, but only in aesthetic chat mode.

**Comment by NintendoManiac64** [comment]
I only meant shift+enter only for when there's no typed message at all, and primarily for the non-aesthetic chat mode since I tend to just stay on "edit" mode permanently rather than toggle back-and-forth.

...this does actually mean that I have no problems with aesthetic chat mode other than you can't edit in it.

**Comment by LostRuins** [comment]
still not a good idea in multilined mode. what if the user just wants to send a single newline? it would no longer be possible.

**Comment by NintendoManiac64** [comment]
I think you're misunderstanding.

So my logic is to use the current behavior, but with a single exception that, if there's literally nothing typed *at all* in the message box, then shift+enter has the chat box generate a new message.

The idea is that the user would never begin a message with a linebreak, e.g.:
```

this is an example of a message that begins with a linebreak
```

**Comment by LostRuins** [comment]
my point is, sometimes they actually do, especially when writing stories. maybe less common for chat, but it's perfectly fine to want to add some newlines after the main story or adventure prompt.

**Comment by NintendoManiac64** [comment]
Oh. huh. I did not know that, but I am *very much* not the author/writer type, so what do I know?

I don't suppose there are any sort of other keyboard shortcuts that are possible?

**Comment by LostRuins** [comment]
I think the current behavior is mostly fine. If you want to send blank messages, now a simple Enter button will do so in chat mode. And for normal mode, this is usually a very uncommon requirement - pressing the submit button manually would be warranted in those cases. If you really only want to use the keyboard, a trick may be to send an empty space and then enable "Trim Whitespaces" in options, which would trim it back to empty anyway.

Just wondering, what's the issue with using tabs or the mouse cursor to select the "Submit" button? Is it somehow inaccessible?

**Comment by NintendoManiac64** [comment]
I'll be honest, I wasn't even sure what the "Trim Whitespaces" setting was supposed to do... I'll give that a whirl.

Regarding Tab, it's mainly that going back from "Send" to the message box requires... uh, hang on I need to count... pressing Tab 23 times.

As for using the mouse, well, it's just that I'm a moderately fast typist at 70-80 words per minute.

**Comment by NintendoManiac64** [comment]
> a trick may be to send an empty space and then enable "Trim Whitespaces" in options, which would trim it back to empty anyway.

I tried this and it causes the "You" to still appear, albeit with no message at all.  Do you know if the end-result from the chat bot is the same compared to if you had instead had the chat bot just generate another message?
