### ISSUE TITLE
Typo in "Memory" for the 'Class Reunion' scenario

### ISSUE THREAD

**Issue by NintendoManiac64** [kaihordewebui/kaihordewebui.github.io#20]
Simply put, there's a typo in the "Memory" for the `Class Reunion` scenario:

> [You are in a class reunion, meeting a group of old former schoolmates. The following is a group conversation **bewteen** you and your friends.]

It should be `between` and not "bewteen"

**Comment by LostRuins** [comment]
very good catch, thanks

**Comment by LostRuins** [comment]
fixed.
