### ISSUE TITLE
Rename "Back" to "Undo"

### ISSUE THREAD

**Issue by NintendoManiac64** [kaihordewebui/kaihordewebui.github.io#3]
I only just realized like a day or two ago that the "Back" and "Redo" buttons, from what I can tell, are supposed to act just like standard "Undo" and "Redo" buttons do in tons of software going back decades.

However, the standard relationship between "Undo" and "Redo" was lost on me (and perhaps others as well?) due to naming it "Back" instead of "Undo", making me think that they're relatively separate functions and, in fact, having "Redo" and "Retry" almost be synonyms linguistically was making me associate those two functions more-so than "Back" and "Redo".

One thing in particular is that the term "Back" makes me expect that the newest message would always get removed in the context of going `back` to before a given line was generated at all, but this doesn't happen if you had last clicked "Retry" because the "Back" button more accurately performs an undo function, so it instead shows what the previously-generated attempt from before you clicked "Retry"

So yeah, proposal to rename "Back" to "Undo"?

　

(also, I personally think "Redo" and "Retry" should be separated, maybe like moving "Add Img" to between them so that it's: Undo; Redo; Add Img; Retry; or maybe change their colors and/or add some symbols to make the undo/redo association be more clear?)

**Comment by LostRuins** [comment]
I actually agree with renaming **Back** to **Undo**. It was labelled as **Back** for legacy reasons as the official kobold UI1 was doing that too - but undo does sound clearer and since they've been turned into symbols in UI2, I think renaming it would be fine.. 

However I don't plan to change the button orders as people will already be familiar with the current layout.

**Comment by henk717** [comment]
The back name is being used because its technically not an undo. It won't undo a user edit for example it goes one action back.

**Comment by LostRuins** [comment]
Actually henk is right. If the user does make an edit then they'd expect it to undo the change, but it doesn't work like that.
I will switch it back to "Back".

I don't want to mess with the way action history works. I want to keep it consistent with the main kobold client.
